#!/bin/bash

set -e
set -x

# THIS RUNS ON THE STICK
PATH=`pwd`/../tamago-go/bin:$PATH
export TAMAGO=`pwd`/../tamago-go/bin/go 
make CROSS_COMPILE=arm-none-eabi- TARGET=usbarmory boot

hit control-C on linux or return on mac
read i
which go
# this build step gives network time to come up
# the real action seems to be in p9 now
# THIS RUNS ON THE HOST
(cd ./p9 && go build) #go build -o t9 main_other.go  nine.go t9.go fn.go  #devgpio.go 

sleep 2
sudo ifconfig en8 10.0.0.2
./p9/p9 10.1:564 l/
#armory-boot-usb -i example.imx -t 400


